[mypy]
show_column_numbers=True
pretty=False

mypy_path=./typings

show_error_codes=True
disallow_any_unimported=True
disallow_any_expr=False
disallow_any_decorated=False
disallow_any_explicit=False
disallow_any_generics=True
disallow_subclassing_any=True

disallow_untyped_calls=True
disallow_untyped_defs=True
disallow_incomplete_defs=True
check_untyped_defs=True
disallow_untyped_decorators=False

no_implicit_optional=True
strict_optional=True

warn_redundant_casts=True
warn_unused_ignores=True
warn_no_return=True
warn_return_any=True
warn_unreachable=True

strict_equality=True

ignore_missing_imports=False

[mypy-pytest.*]
ignore_missing_imports = True
