#!/bin/bash

set -ex

# format code
if [[ $CI ]]; then
    ./.venv/bin/black --check .
    ./.venv/bin/isort --check-only
else
    ./.venv/bin/black .
    ./.venv/bin/isort -y
fi

./.venv/bin/mypy .

./.venv/bin/flake8 flake8_pie test*

